### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './temp/imdb.synonyms'

### ISSUE THREAD

**Issue by ForeverZyh** [dongxinshuai/ASCC#2]
Hi,

When I run the script it fails with the following error

```
Traceback (most recent call last):
  File "./train_imdb_ascc.py", line 310, in <module>
    main()
  File "./train_imdb_ascc.py", line 305, in main
    train_iter, dev_iter, test_iter, syn_data = imdb_make_synthesized_iter(opt)
  File "/repos/ASCC/dataHelper.py", line 1013, in imdb_make_synthesized_iter
    f=open(filename,'rb')
  File "/anaconda3/envs/ascc/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './temp/imdb.synonyms'
```

Could you please provide the `imdb.synonyms`?

**Comment by dongxinshuai** [comment]
Hi,

You may add "--synonyms_from_file false" when the first run.

**Comment by ForeverZyh** [comment]
Thanks! BTW, does the script `train_imdb.sh` reproduce the results in Table 1?
